version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.15.4
    container_name: gitea
      # - GITEA__database__DB_TYPE=mysql
      # - GITEA__database__HOST=db:3306
      # - GITEA__database__NAME=gitea
      # - GITEA__database__USER=gitea
      # - GITEA__database__PASSWD=gitea
      # - GITEA__mailer__ENABLED=true
      # - GITEA__mailer__FROM=${GITEA__mailer__FROM:?GITEA__mailer__FROM not set}
      # - GITEA__mailer__MAILER_TYPE=smtp
      # - GITEA__mailer__HOST=${GITEA__mailer__HOST:?GITEA__mailer__HOST not set}
      # - GITEA__mailer__IS_TLS_ENABLED=true
      # - GITEA__mailer__USER=${GITEA__mailer__USER:-apikey}
      # - GITEA__mailer__PASSWD="""${GITEA__mailer__PASSWD:?GITEA__mailer__PASSWD not set}"""
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
